### ISSUE TITLE
Console doesn't scroll correctly

### ISSUE THREAD

**Issue by Candid-Moe** [Zeal8bit/Zeal-WebEmulator#15]
When the input line reach the bottom, the input area get hidden behind the *Disassemble - Memory - Terminal* ear tabs. 
This happens even if you use *Ctrl -* to zoom out the whole page.
![image](https://github.com/Zeal8bit/Zeal-WebEmulator/assets/172752004/d4cf7891-a496-4716-8963-f1c2042f8012)

**Comment by Zeal8bit** [comment]
Hello @Candid-Moe,
Thanks for reporting the issue, I am not satisfied the layout of the page at the moment it is not modular enough and on small screen, this issue happens a lot.

I will have a quick try fixing this issue on the short term and on the longer term, I am thinking about making each part of the emulator view a resizable and movable window. 

If you have any suggestion, feel free to tell me

**Comment by Candid-Moe** [comment]
![emulador](https://github.com/user-attachments/assets/a18e2d19-6215-4e91-afa1-40833a74ac4e)
- Put "Settings" in the hamburger menu (probably with "files/images to load")
- Divide bottom in three panes, side by side: disassembly, memory and buttons (debugging + uart). This concentrate all the action in the same horizontal line. There is space to watch code + memory (with real time update if possible), even on small screens.
- Register aligned to the bottom, just over disassembly. Alternative: put them in an horizontal stripe between screen and disassembly/memory/buttons.

I prefer all in one page.
