### ISSUE TITLE
"exec" hangs with a non-existent file in H:

### ISSUE THREAD

**Issue by Candid-Moe** [Zeal8bit/Zeal-WebEmulator#16]
The "exec xxx.bin" command hangs up if file doesn't exists, but only when in H: (mapped to PC directory)
![Screenshot at 2024-07-17 11-31-33](https://github.com/user-attachments/assets/4ac81368-509c-489d-a64b-231c100bd9fd)

**Comment by Zeal8bit** [comment]
Fixed on `master`, thanks for reporting this issue!
