### ISSUE TITLE
cd h:/ fails after waiting a few seconds.

### ISSUE THREAD

**Issue by Candid-Moe** [Zeal8bit/Zeal-WebEmulator#17]
If you type "cd h:/" and doesn't immediately click in the "Specify the directory to use as a virtual disk" dialog, the command fail after clicking the OK button:
![Screenshot at 2024-07-17 16-54-54](https://github.com/user-attachments/assets/37079771-5fff-4c37-b280-bc401d1b4bd1)

**Comment by Zeal8bit** [comment]
@Candid-Moe Thanks for reporting this issue too, I was able to reproduce it on my side, I am going to investigate

**Comment by Zeal8bit** [comment]
The API used for showing the folder picker is a picky, it absolutely required the function to come from a user action (click, keypress, etc...). I am not 100% sure it is failing if we take time before clicking the alert window, but I got entirely rid of the alert and used the emulator's popup API I implemented before, this issue should not occur anymore
