### ISSUE TITLE
Breakpoint list can contains duplicates

### ISSUE THREAD

**Issue by Candid-Moe** [Zeal8bit/Zeal-WebEmulator#18]
User can insert a duplicate breakpoint, which can result in breakpoint always active.

Anyway, it will be sweet adding a command to delete a breakpoint or all of them.
![Screenshot at 2024-07-19 07-55-44](https://github.com/user-attachments/assets/d63e29e4-37c1-4a66-a65f-e2bdc861b9de)

**Comment by Zeal8bit** [comment]
@Candid-Moe Thanks for reporting this issue!

I just pushed a fix for that
