### ISSUE TITLE
How to clear screen?

### ISSUE THREAD

**Issue by Candid-Moe** [Zeal8bit/Zeal-WebEmulator#19]
I need to clear the screen under emulation. How do I do it? Are there other capabilities available?

**Comment by Zeal8bit** [comment]
Hello @Candid-Moe ,

If you are running a program under Zeal 8-bit OS, there is an `ioctl` that lets you clear the screen: https://github.com/Zeal8bit/Zeal-8-bit-OS/blob/main/kernel_headers/sdcc/include/zos_video.h#L39

If you are running a bare metal program, you'll need to clear the screen manually: map both tilemap layers and `memset` them
