### ISSUE TITLE
I need to specify four files to load my own ROM

### ISSUE THREAD

**Issue by Candid-Moe** [Zeal8bit/Zeal-WebEmulator#20]
To upload my own image, I need to specify all four files, including EEPROM and CompactFlash images (which I don't have), otherwise the "Read Files" button doesn't turn active.

![Screenshot at 2024-08-06 15-04-51](https://github.com/user-attachments/assets/755ab300-6f1e-4bce-acd0-7b28f7007b3b)

I think the button must be active regardless of the number of files indicated (one at least).

**Comment by Zeal8bit** [comment]
Hello @Candid-Moe ,

Despite the design of the button, it is always active. Thus, you can actually specify any number of file you want. If you want to only specify the ROM disk, that's possible for example.
