### ISSUE TITLE
Focus lost when pressing buttons, tabs

### ISSUE THREAD

**Issue by Candid-Moe** [Zeal8bit/Zeal-WebEmulator#29]
When you press any button or ear tab you lost the current focus, which is annoying, inconvenient and unnecessary.

In emulation the focus must stay in the current input area unless you click on another input area.

Also, after reset, the focus must be in the screen area.

**Comment by Zeal8bit** [comment]
Hello @Candid-Moe ,

I understand that this behavior is irritating, the thing is the canvas is just one element of the page, just like the buttons and other elements. I am not sure what would be the best solution, if the key(board) listener would be put on the whole page, any key typed or shortcuts pressed would be redirected and interpreted by the emulated Zeal.
If the focus is forced to the canvas every time a click occur on the page, it can also be frustrating if you are trying to type something (breakpoint address, memory view addres, etc..)
