### ISSUE TITLE
Pause button doesn't change to Run button when paused by breakpoint

### ISSUE THREAD

**Issue by Candid-Moe** [Zeal8bit/Zeal-WebEmulator#32]
When execution reach a breakpoint, the run/pause button doesn't change to Run automatically.

Also, when a user program starts, the Run button doesn't change to Pause.

More precisely, the state of the RUN/PAUSE button must match the state of the emulator (running or paused).

**Comment by Zeal8bit** [comment]
@Candid-Moe Thanks for reporting this issue, it should now be fixed, feel free to reopen in case you encounter similar issue.
